name: 'Quality tester: Remote self-hosted machine'

on:
  push:
    paths:
      - '.github/workflows/evaluate_remote_selfhost.yml'
      - 'src/*'
      - 'client/*'
      - 'data/*'
      - 'Makefile'
      - 'models/*'

jobs:
  evaluate:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - name: Clean the environment
      run: sudo make clean
    - name: Evaluation
      run: make evaluate
    - name: Metrics by file
      run: cat client/reports/*/metrics_by_file.csv
    - name: Upload artifacts to dashboard
      env:
        DASH_SSH_KEY: ${{ secrets.DASH_SSH_KEY }}
        DASH_SSH_USER: ${{ secrets.DASH_SSH_USER }}
        DASH_SSH_HOST: ${{ secrets.DASH_SSH_HOST }}
      run: |
        echo "$DASH_SSH_KEY" > ./id_rsa_dash
        chmod 400 ./id_rsa_dash
        ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ./id_rsa_dash ${DASH_SSH_USER}@${DASH_SSH_HOST} "mkdir -p /home/ubuntu/ml-quality-cicd/results"
        scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ./id_rsa_dash client/reports/*/metrics_by_file.csv ${DASH_SSH_USER}@${DASH_SSH_HOST}:/home/ubuntu/ml-quality-cicd/results/$(echo ${GITHUB_SHA} | cut -c1-7).csv
    - name: Clean the environment
      run: sudo make clean
